notifications:
  email:
    recipients:
      - elveestei@gmail.com
    on_success: never
  
language: objective-c

branches:
  only:
    - cef_3538
    - cef_3578
    - cef_3626
    - cef_3683
    - cef_3729
    - cef_3770
    - cef_3809

xcode_project: CEF.swift.xcodeproj
xcode_scheme: CEF.swift
osx_image: xcode10.1

before_install:
  - brew update
  - brew install jq
  - sudo pip install lxml
  
install:
  - ./scripts/setup.sh
  - ./scripts/check_proxy_impl.py ./External/cef_binary/include/ ./CEF.swift/Proxies/
  - ./scripts/check_handler_interface.py ./External/cef_binary/include/ ./CEF.swift/Handlers/

script: set -o pipefail && xcodebuild clean build -project CEF.swift.xcodeproj -scheme CEF.swift | xcpretty
