notifications:
  email:
    recipients:
      - elveestei@gmail.com
    on_success: never
  
language: objective-c

branches:
  only:
    - cef_4280
    - cef_4389
    - cef_4430
    - cef_4472
    - cef_4515

xcode_project: CEF.swift.xcodeproj
xcode_scheme: CEF.swift
osx_image: xcode10.1
os: osx

before_install:
  - brew install jq
  
install:
  - ./scripts/setup.sh
  - ./scripts/check_proxy_impl.py ./External/cef_binary/include/ ./CEF.swift/Proxies/
  - ./scripts/check_handler_interface.py ./External/cef_binary/include/ ./CEF.swift/Handlers/

script: set -o pipefail && xcodebuild clean build -project CEF.swift.xcodeproj -scheme CEF.swift | xcpretty
