notifications:
  email:
    recipients:
      - elveestei@gmail.com
    on_success: never
  
language: objective-c

branches:
  only:
    - cef_3987
    - cef_4044
    - cef_4103
    - cef_4147
    - cef_4183
    - cef_4240
    - cef_4280
    - ci-test

xcode_project: CEF.swift.xcodeproj
xcode_scheme: CEF.swift
osx_image: xcode11.3

before_install:
  - brew update
  - brew install jq
  
install:
  - ./scripts/setup.sh
  - ./scripts/check_proxy_impl.py ./External/cef_binary/include/ ./CEF.swift/Proxies/
  - ./scripts/check_handler_interface.py ./External/cef_binary/include/ ./CEF.swift/Handlers/

script: set -o pipefail && xcodebuild clean build -project CEF.swift.xcodeproj -scheme CEF.swift | xcpretty
